" Sections according to :options

" 0 variables
" ===========
" {{{
let $VIM_CONFIG_HOME=$XDG_CONFIG_HOME . '/vim'
let $VIM_CACHE_HOME=$XDG_CACHE_HOME . '/vim'
" }}}


" 1 important
" ===========
" {{{
set nocompatible
set cpoptions+=$               " Show boundaries of to be changed text
set packpath+=$VIM_CONFIG_HOME/pack
" }}}


" 2 moving around, searching and patterns
" =======================================
" {{{
set incsearch             " enable incremental search
set ignorecase            " use case insensitive search,
set smartcase             " except when using capital letters
set startofline           " jump commands go to first char in line
set noautochdir           " some plugins don't like this enabled (vimshell)
" }}}


" 4 displaying text
" =================
" {{{
set scrolloff=3        " number of screen lines to show around the cursorline
set nowrap
set linebreak          " wrap long lines at a character in 'breakat'
set cmdheight=2
set list               " show whitespace characters
set listchars=tab:↹\ ,trail:·,eol:¬
set number
set numberwidth=3
set relativenumber         " line numbers relative to current line
" }}}


" 5 syntax, highlighting and spelling
" ===================================
" {{{
syntax on
set hlsearch
set cursorline
let &colorcolumn=join(range(80,999), ",")
set nospell
filetype plugin indent on                      " identify syntax by filetype
" }}}


" 6 Multiple Windows
" ==================
" {{{
set laststatus=2       " always show a status line
set hidden             " don't unload a buffer when no longer shown in a window
set winheight=5        " set this before winminheight
set winwidth=90        " width for active window
set winminheight=5
set winheight=999      " height of active window
set splitright
set switchbuf=usetab   " Reuse windows/tabs when switching buffers
" }}}


" 7 Multiple Tab Pages
" ====================
" {{{
set showtabline=2
" }}}


" 8 terminal
" ==========
" {{{
set termguicolors
set title                     " enable title in console
" }}}


" 9 using the mouse
" =================
" {{{
set mouse=a
set mousehide
" }}}


" 11 messages and info
" =====================
" {{{
set showcmd                              " Show typed commands in status line
set ruler
set showmode
set confirm
set visualbell                           " Use visual bell instead of beeping
" }}}


" 14 editing text
" ===============
" {{{
set backspace=indent,eol,start       " Allow backspacing over autoindent,
                                     " Line breaks and start of insert action
set nrformats-=octal                 " No octal numbers with leading 0
set showmatch                        " Highlight matching braces
set textwidth=0                      " Don't force a max textwidth
" Complete in insert mode from:
"   current, all windows, all other buffers, tags
set complete=.,w,b,t
" }}}


" 15 Tabs and Indenting
" =====================
" {{{
set expandtab                 " Expand tabs to spaces
set smartindent               " Smart indenten based on blocks
set autoindent                " Autointend with '='; '=G' for the entire file
set shiftwidth=2              " Number of spaces to replace a tab with
set softtabstop=2             " Tabsize in insert mode
set tabstop=2                 " Width of the tab character
set shiftround                " Round indentation to multiple of shiftwidth
" }}}


" 16 Folding
" ==========
" {{{
set foldmethod=syntax
set foldmarker={{{,}}}
set foldcolumn=2
set foldlevel=1
set foldlevelstart=1
set foldnestmax=3
" }}}


" 18 Mapping
" ==========
" {{{
set notimeout ttimeout ttimeoutlen=50        " Quickly time out on keycodes,
                                             " but never time out on mappings
" }}}


" 19 reading and writing file
" ===========================
" {{{
if exists('$SUDO_USER')
    set nobackup
    set nowritebackup
else
    set backup
    set backupdir=$VIM_CACHE_HOME/backup
    set backupdir+=/tmp
    set backupdir+=.
endif
set autowriteall
set nomodeline                             " Disable modeline nonsense
set modelines=0
" }}}


" 20 the swap file
" ================
" {{{
if exists('$SUDO_USER')
    set noswapfile
else
    set swapfile
    set directory=$VIM_CACHE_HOME/swap
    set directory+=/tmp
    set directory+=.
endif
set updatecount=80     " Update swapfile every X chars
" }}}


" 21 Command Line Editing
" =======================
" {{{
if exists('$SUDO_USER')
    set noundofile
else
    set undofile
    set undodir=$VIM_CACHE_HOME/undo
    set undodir+=/tmp
    set undodir+=.
endif
set history=100

set wildmenu
set wildmode=list:longest
set wildignorecase                             " Ignore case in filenames
set wildignore=*.o,*.obj,*~,*.pyc,*.exe,*.dll,*.manifest
set wildignore+=*.aux,*.out,*.toc
set wildignore+=.env
set wildignore+=.env[0-9]+
set wildignore+=.git,.gitkeep,.hg,.svn
set wildignore+=.tmp
set wildignore+=.coverage
set wildignore+=*DS_Store*
set wildignore+=.sass-cache/
set wildignore+=__pycache__/
set wildignore+=vendor/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=.idea/**
set wildignore+=node_modules/**
set wildignore+=*.so,*.swp,*.zip,*/.Trash/**
set wildignore+=*.pdf,*.dmg,*/Library/**,*/.rbenv/**
set wildignore+=*/.nx/**,*.app
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg
set wildignore+=*.DS_Store,desktop.ini
" }}}


" 22 Executing External Commands
" ==============================
" {{{
if has('unix')
  set shell=bash
elseif has('win32')
  set shell=cmd.exe
endif

if exists('+shellslash')
  set shellslash                            " win32: use forward slash in paths
endif
" }}}


" 25 Various
" ==========
" {{{
if exists('$SUDO_USER')
    set viminfo=
else
    set viminfo+=n$VIM_CACHE_HOME/viminfo
endif
" }}}


" 26 Multi-Byte Characters
" ========================
" {{{
set encoding=utf-8                              " Encoding for displaying files
set fileencoding=utf-8                          " Encoding for writing files
set fileformat=unix                             " Set default fileformat
set fileformats=unix                            " Set possible fileformats
" }}}


" 27 Various
" ==========
" {{{
set gdefault                               " Substitute globally by default
set sessionoptions-=help                   " Don't want to restore help buffers
set virtualedit=block,onemore
" }}}


" Plugins
packloadall
source $VIM_CONFIG_HOME/plugin/plug-settings.vim

